// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJbiK7fOdPi8Xp6pUsbvvRpEegmQ7ftgo',
    appId: '1:695176280176:web:7b8e26b532992a0d0e5cb5',
    messagingSenderId: '695176280176',
    projectId: 'final-work-pap',
    authDomain: 'final-work-pap.firebaseapp.com',
    storageBucket: 'final-work-pap.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyYY5BCsGPnoA4AV36_LrtQQNvvdPbHpg',
    appId: '1:695176280176:android:6880581bbece66210e5cb5',
    messagingSenderId: '695176280176',
    projectId: 'final-work-pap',
    storageBucket: 'final-work-pap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFq7ZHu6ZhZPuJuWPjwldGAa9bsbu9li8',
    appId: '1:695176280176:ios:7b20d3835f30e3420e5cb5',
    messagingSenderId: '695176280176',
    projectId: 'final-work-pap',
    storageBucket: 'final-work-pap.firebasestorage.app',
    iosBundleId: 'com.example.finalWorkPap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFq7ZHu6ZhZPuJuWPjwldGAa9bsbu9li8',
    appId: '1:695176280176:ios:7b20d3835f30e3420e5cb5',
    messagingSenderId: '695176280176',
    projectId: 'final-work-pap',
    storageBucket: 'final-work-pap.firebasestorage.app',
    iosBundleId: 'com.example.finalWorkPap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJbiK7fOdPi8Xp6pUsbvvRpEegmQ7ftgo',
    appId: '1:695176280176:web:01cd4ddae7daf4e70e5cb5',
    messagingSenderId: '695176280176',
    projectId: 'final-work-pap',
    authDomain: 'final-work-pap.firebaseapp.com',
    storageBucket: 'final-work-pap.firebasestorage.app',
  );
}
